#!/usr/bin/env python
# Main script for running
import argparse
import sys

tasks = {
    'markerplace': 'Place marker',
    'metpred': 'Predict'
}

def buildcmNetwork(cmdArgs):
    """ Create community metabolic network from HMP.

    Args:
        cmdArgs (dictionary): args["folder", "output"]

    Returns: TODO

    """
    parser = argparse.ArgumentParser(
              description="",
              usage="")

    parser.add_argument("-k", type=int, help='k-mer size to use', default=4)
    parser.add_argument("-o", "--output", required=True)

    args = parser.parse_args(cmdArgs)

    print("Success")

def metabolic_prediction():
    parser = argparse.ArgumentParser(
              description="Map normalize classified reads table to table",
              usage="cmnet metpred ")

    parser.add_argument("-i", type=str)



def markerplacement():
    """ Place genus to the closest one.

    Returns: TODO

    """
    parser = argparse.ArgumentParser(
              description="",
              usage=""
            )

def print_help_and_exit():
    print('')
    sys.exit(0)

def main():
    """ Main entry for commandline
    """

    usage_s = """cmnet <command> [args]"""
    task = sys.argv.pop(1)

    if task not in tasks:
        print_help_and_exit()

    tasks[task]()  # Run task
    return 0


if __name__ == '__main__':
    if len(sys.argv) == 1:
        exit(1)
    retCode = main()
    exit(retCode)
