#!/usr/bin/env python
# Main script for running
import argparse
import sys

tasks = {
    'markp': "Place marker to the metabolic model",
    'metp': "Predict metabolic from place marker",
    'mbuild': "Build metabolic network"
}


def markerplacement():
    """ Place genus to the closest one.

    Returns: TODO

    """
    parser = argparse.ArgumentParser(
              description="",
              usage=""
            )

def print_help_and_exit():
    print('CMNet - Community Metabolic Network predictor from')
    print('\nUsage: cmnet <command> [options] <arguments>')
    print('\nAvailable command')
    for task in tasks.keys():
        print("{} - {}".format(task, tasks[task]))
    sys.exit(0)

def main():
    """ Main entry for commandline
    """

    usage_s = """cmnet <command> [args]"""
    task = sys.argv.pop(1)

    if task not in tasks:
        print_help_and_exit()

    import importlib
    taskmodule = importlib.import_module("cmnet.tasks.{}".format(task))
    taskmodule.run()
    return 0


if __name__ == '__main__':
    if len(sys.argv) == 1:
        print_help_and_exit()
    retCode = main()
    exit(retCode)
