#!/usr/bin/env python
# Main script
import argparse
import sys

tasks = {
    'markp': "Calculate function abundance from microbial communities",
    'listmodel': "List all available models"
}


def print_help_and_exit():
    print('METGEM - A python toolbox for metabolic model-based fucntional prediction from microbial communities')
    print('\nUsage: metgem <command> [options] <arguments>')
    print('\nAvailable command')
    for task in tasks.keys():
        print("{} - {}".format(task, tasks[task]))
    sys.exit(0)


def main():
    """ Main entry for commandline
    """

    task = sys.argv.pop(1)

    if task not in tasks:
        print_help_and_exit()

    import importlib
    taskmodule = importlib.import_module("metgem.tasks.{}".format(task))
    taskmodule.run()
    return 0


if __name__ == '__main__':
    if len(sys.argv) == 1:
        print_help_and_exit()
    retCode = main()
    exit(retCode)
